# This file is a template, and might need editing before it works on your project.
# This file is a template, and might need editing before it works on your project.
image: python3.6:latest

before_script:
  - python -V                                   # Print out python version for debugging

test:
  script:
  - pip install -r requirments.py
 
  
run:
  script:
  # run the command here 
  - python3.6 -m unittest discover -v
  artifacts:
    paths:
    - dist/*.whl


