#!/bin/bash 

echo "Installing requirements.."

pip3 install --upgrade setuptools
pip3 install -r ../requirements.txt

# Make executable
chmod +x panoptes.py

# If the directory does not exist make it
if [ ! -d /var/log/panoptes/ ]; then
    mkdir /var/log/panoptes/
fi

# If the directory does not exist make it
if [ ! -d /etc/panoptes/ ]; then
    mkdir /etc/panoptes/
fi

# Create config from example
if [ ! -f config.json ]; then
    echo "Config.py created"
    cp resources/config.example config.json
else
    echo "Using old config"
fi

# Configure boot file
# Used "?" for sed seperator here because "/" was 
# causing problems beacuse appears in the path
cat update | sed "s?"cd\ REPO"?"cd\ `pwd`"?" > update

cp update /etc/panoptes/update

# Create a new cron for updates
# Write out current crontab
crontab -l > /tmp/panoptes_cron
# Append new cron into cron file
echo "* * * * *" /etc/panoptes/update >> /tmp/panoptes_cron
# Install new cron file
crontab /tmp/panoptes_cron
rm /tmp/panoptes_cron

# Configure boot file
# Used "?" for sed seperator here because "/" was 
# causing problems beacuse appears in the path
cat resources/panoptes | sed "s?"cd\ REPO"?"cd\ `pwd`"?" > resources/panoptes

# Add to start on boot
cp resources/panoptes /etc/init.d/
update-rc.d panoptes defaults
