#!/bin/bash

python3.6 plugins/packet_stats.py start
python3.6 plugins/system_stats.py start
python3.6 plugins/ping_metric.py start
python3.6 plugins/ap_metrics.py start
python3.6 plugins/nodes_up.py start
